/**
 * @file preferencesdialog.h
 * @author Laurent Georget
 * @date 2015-06-07
 * @brief Definition of class PreferencesDialog
 */
#ifndef PREFERENCESDIALOG_H
#define PREFERENCESDIALOG_H

#include <QDialog>

/**
 * @brief This namespace contains code autogenerated by QtDesigner.
 */
namespace Ui {
	/**
	 * @brief This class is the graphical user interface class generated
	 * by QtDesigner
	 */
	class PreferencesDialog;
}

/**
 * @brief This class is a preferences dialog which is open before the main
 * window to let the user select its project.
 *
 * Three settings are necessary to begin the exploration of a project:
 * <ul>
 * <li>the source tree</li>
 * <li>a database containing the function symbols of the project</li>
 * <li>the directory where all diagrams are stored for the project</li>
 * </ul>
 */
class PreferencesDialog : public QDialog
{
	Q_OBJECT

public:
	/**
	 * @brief Constructor.
	 *
	 * @param parent the parent widget
	 */
	explicit PreferencesDialog(QWidget *parent = 0);
	/**
	 * @brief Destroy the dialog window and its components.
	 */
	~PreferencesDialog();

public slots:
	/**
	 * @brief Closes the dialog and configures the application with the
	 * current settings.
	 */
	void accept();
	/**
	 * @brief Opens a dialog to let the user select the source tree
	 * directory.
	 */
	void selectSourceTree();
	/**
	 * @brief Opens a dialog to let the user select the functions database.
	 */
	void selectDatabase();
	/**
	 * @brief Opens a dialog to let the user select the diagrams directory.
	 */
	void selectDiagramsDir();

private:
	/**
	 * @brief the graphical user interface generated by QtDesigner
	 */
	Ui::PreferencesDialog *ui;
};

#endif // PREFERENCESDIALOG_H
